"use client";
import { useLayoutEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useLanguage } from "@/components/LanguageProvider";
import { cameraScene } from "@/data/site";
gsap.registerPlugin(ScrollTrigger);
export function CameraScene() {
  const ref=useRef<HTMLElement>(null); const {language, dir}=useLanguage(); const t=cameraScene[language];
  useLayoutEffect(()=>{const el=ref.current;if(!el)return;const enteringFromRight=dir==="rtl";const media=gsap.matchMedia();media.add("(prefers-reduced-motion: no-preference)",()=>{const ctx=gsap.context(()=>{const q=gsap.utils.selector(el);const tl=gsap.timeline({scrollTrigger:{trigger:el,start:"top top",end:"+=260%",pin:true,scrub:1,invalidateOnRefresh:true}});tl.fromTo(q(".camera-object"),{xPercent:enteringFromRight?135:-135,rotate:enteringFromRight?-14:14,scale:.58,opacity:0},{xPercent:0,rotate:0,scale:1,opacity:1,duration:1.1,ease:"power3.out"}).fromTo(q(".camera-ring"),{scale:.25,opacity:0},{scale:1,opacity:1,duration:.8,ease:"none"},"<").fromTo(q(".camera-copy"),{xPercent:enteringFromRight?-75:75,opacity:0},{xPercent:0,opacity:1,duration:.75,ease:"power3.out"},"-=.45").fromTo(q(".camera-beam"),{scaleX:0,transformOrigin:enteringFromRight?"right center":"left center"},{scaleX:1,duration:.7,ease:"power2.out"},"-=.45").to(q(".camera-object"),{xPercent:enteringFromRight?-76:76,rotate:enteringFromRight?10:-10,scale:.72,opacity:0,duration:1,ease:"power2.in"},"+=.6").to(q(".camera-copy"),{y:45,opacity:0,duration:.55,ease:"power2.in"},"<").to(q(".camera-beam"),{scaleX:0,duration:.35},"<");},el);return()=>ctx.revert()});return()=>media.revert()},[dir]);
  return <section ref={ref} className="story-scene camera-scene"><div className="scene-index">03 / {t.label}</div><div className="camera-chapter"><span>01</span><i/><span>{language === "ar" ? "من الكادر إلى الحركة" : "FRAME TO MOTION"}</span></div><div className="camera-object"><div className="camera-body"><div className="camera-top"/><div className="camera-lens-large"><span/></div><div className="camera-grip"/></div><div className="camera-ring"/></div><div className="camera-beam"/><div className="camera-copy"><p className="eyebrow">{t.eyebrow}</p><h2>{t.title}</h2><p>{t.body}</p></div><div className="camera-notes"><span>{language === "ar" ? "ضوء / حركة / تكوين" : "LIGHT / MOVEMENT / COMPOSITION"}</span><span>REC 04:02:18</span></div><div className="scene-time">00:00:12:18</div></section>;
}